# Generated by Django 2.0.5 on 2018-06-07 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('appname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=32)),
                ('ip', models.GenericIPAddressField(db_index=True, protocol='ipv4')),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('groupname', models.CharField(max_length=32)),
                ('ug_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.Host')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='h_a',
            field=models.ManyToManyField(to='a.Host'),
        ),
    ]
