# Generated by Django 2.0.5 on 2018-06-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0002_usergroup_ug_u'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='ug_h',
        ),
    ]
